# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: uka.pgr@gmail.com
author_name: odin-hoang
preset_name: starter
project_name: veline-fs-frontend

