# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: uka.pgr@gmail.com
author_name: odin-hoang
contract_name: veline_contract
deployment_language: python
preset_name: starter
project_name: veline-fs-contracts

